# Generated by Django 4.1.3 on 2022-11-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=20)),
                ('sexo', models.CharField(choices=[('1', 'M'), ('2', 'F')], max_length=1)),
                ('ci', models.IntegerField()),
                ('dir', models.TextField()),
                ('tel', models.IntegerField()),
                ('grupo', models.IntegerField()),
                ('anno', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')])),
            ],
        ),
    ]
