# Generated by Django 4.1.3 on 2022-11-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='anno',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)]),
        ),
    ]
